# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/

site_name: Friday Bot Docs
site_url: https://docs.friday-bot.com
docs_dir: docs
repo_url: https://github.com/Brettanda/friday-docs
repo_name: brettanda/friday-docs
edit_uri: ''
copyright: Copyright &copy; 2020 - 2022 Brett Anda
theme:
  name: material
  locale: en
  highlightjs: true
  language: en
  logo: images/friday-logo-circle-150.png
  favicon: images/friday-logo-circle-32.ico 
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.instant # caches everything on live site
    - navigation.sections
    - navigation.tabs
    # - navigation.indexes
    - search.suggest
    # - search.highlight
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - macros
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true 
  # - footnotes
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  # - javascripts/config.js
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
extra:
  homepage: https://friday-bot.com
  analytics:
    provider: google
    property: UA-142551610-4
  version:
    default: dev
    provider: mike
  # alternate:
  #   - name: English
  #     link: /en/
  #     lang: en
  social:
    - icon: fontawesome/solid/globe
      link: //brettanda.ca
    - icon: fontawesome/brands/github
      link: //github.com/Brettanda
    - icon: fontawesome/brands/discord
      link: //discord.gg/XP4avQ449V
    - icon: fontawesome/brands/patreon
      link: //www.patreon.com/fridaybot
nav:
  - Home:
    - Home: index.md
    - FAQ: faq.md
  - Chat:
    - Chat: chat/index.md
    - Commands: commands/chat.md
  - Moderation:
    - Moderation: commands/moderation.md
    - Automod: commands/automod.md
    - Logging: commands/logging.md
    - Welcome: commands/welcome.md
  - Media:
    - Music: commands/music.md
    - Redditlinks: commands/redditlink.md
  - Premium:
    - Patreon: commands/patreons.md
    - Voting: commands/topgg.md
  - Fun:
    - Games: commands/fun.md
    - Dice: commands/dice.md
    - Meme: commands/meme.md
  - Utilities:
    - General: commands/general.md
    - Issue: commands/issue.md
    - Support: commands/support.md
    - Ping: commands/ping.md
    - Reminders: commands/reminder.md
    - Starboard: commands/stars.md