name: GitHhub pages
on:
  push:
    branches:
      - master 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-friday-docs-dependencies
        with:
          path: |
            ${{ env.pythonLocation}}/lib/python${{ matrix.python-version }}/site-packages/*
            ~/venv
          key: ${{ matrix.os }}-pip-${{ env.cache-name }}-${{ hashfiles('requirements.txt') }}
          restore-keys: |
            ${{ matrix.os }}-pip-${{ env.cache-name }}-${{ hashfiles('requirements.txt') }}
            ${{ matrix.os }}-pip-${{ env.cache-name }}-
            ${{ matrix.os }}-pip-
            ${{ matrix.os }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv ~/venv
          . ~/venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - run: |
          . ~/venv/bin/activate
          mkdocs gh-deploy --force
